import networkx as nx
import matplotlib.pyplot as plt
G = nx.Graph()




G.add_nodes_from([("node 1", {"name": "disjoint"}), ("node 2", {"name": "disjointTouch"}),
                  ("node 3", {"name": "meet"}), ("node 4", {"name": "overlapMeet"}),
                  ("node 5", {"name": "overlap"}), ("node 6", {"name": "overlapCoveredBy"}),
                  ("node 7", {"name": "overlapCovers"}), ("node 8", {"name": "coveredBy"}),
                  ("node 10", {"name": "covers"}),
                  ("node 11", {"name": "insideTouch"}), ("node 12", {"name": "coveredByFully"}),
                  ("node 13", {"name": "coversFully"}), ("node 14", {"name": "containsTouch"}),
                  ("node 15", {"name": "inside"}), ("node 16", {"name": "insideTotal"}),
                  ("node 17", {"name": "equals"}), ("node 18", {"name": "containsTotal"}),
                  ("node 19", {"name": "contains"}), ("node 20", {"name": "embrace"}),
                  ("node 21", {"name": "embraceFully"}), ("node 22", {"name": "attach"}),
                  ("node 23", {"name": "disjointTotal"}), ("node 24", {"name": "embraceTouch"}),
                  ("node 25", {"name": "entwinedFully"}), ("node 26", {"name": "meetFully"}),
                  ("node 27", {"name": "entwined"}), ("node 29", {"name": "overlapEntwined"})

                  ])
# Side disjoint to inside
G.add_edge("node 1", "node 2")
G.add_edge("node 2", "node 3")
G.add_edge("node 3", "node 4")
G.add_edge("node 4", "node 5")
G.add_edge("node 5", "node 6")
G.add_edge("node 6", "node 8")
G.add_edge("node 8", "node 11")
G.add_edge("node 11", "node 15")

# Side embrace to contains
G.add_edge("node 20", "node 24")
G.add_edge("node 24", "node 27")
G.add_edge("node 27", "node 29")
G.add_edge("node 29", "node 5")
G.add_edge("node 5", "node 7")
G.add_edge("node 7", "node 10")
G.add_edge("node 10", "node 14")
G.add_edge("node 14", "node 19")

# Top Hat
G.add_edge("node 27", "node 25")
G.add_edge("node 25", "node 22")
G.add_edge("node 22", "node 26")
G.add_edge("node 26", "node 3")

# Bottom Hat
G.add_edge("node 8", "node 12")
G.add_edge("node 12", "node 17")
G.add_edge("node 17", "node 13")
G.add_edge("node 13", "node 10")

#Top Line
G.add_edge("node 20", "node 21")
G.add_edge("node 21", "node 22")
G.add_edge("node 22", "node 23")
G.add_edge("node 23", "node 1")

#Bottom Line
G.add_edge("node 15", "node 16")
G.add_edge("node 16", "node 17")
G.add_edge("node 17", "node 18")
G.add_edge("node 18", "node 19")

nx.draw(G)
plt.show()

spl = dict(nx.all_pairs_shortest_path_length(G))
# 27
# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 12"])
# print(spl["node 1"]["node 13"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 16"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 18"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 21"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 23"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 25"])
# print(spl["node 1"]["node 26"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 29"])

# print(spl["node 2"]["node 1"])
# print(spl["node 2"]["node 2"])
# print(spl["node 2"]["node 3"])
# print(spl["node 2"]["node 4"])
# print(spl["node 2"]["node 5"])
# print(spl["node 2"]["node 6"])
# print(spl["node 2"]["node 7"])
# print(spl["node 2"]["node 8"])
# print(spl["node 2"]["node 10"])
# print(spl["node 2"]["node 11"])
# print(spl["node 2"]["node 12"])
# print(spl["node 2"]["node 13"])
# print(spl["node 2"]["node 14"])
# print(spl["node 2"]["node 15"])
# print(spl["node 2"]["node 16"])
# print(spl["node 2"]["node 17"])
# print(spl["node 2"]["node 18"])
# print(spl["node 2"]["node 19"])
# print(spl["node 2"]["node 20"])
# print(spl["node 2"]["node 21"])
# print(spl["node 2"]["node 22"])
# print(spl["node 2"]["node 23"])
# print(spl["node 2"]["node 24"])
# print(spl["node 2"]["node 25"])
# print(spl["node 2"]["node 26"])
# print(spl["node 2"]["node 27"])
# print(spl["node 2"]["node 29"])


# print(spl["node 3"]["node 1"])
# print(spl["node 3"]["node 2"])
# print(spl["node 3"]["node 3"])
# print(spl["node 3"]["node 4"])
# print(spl["node 3"]["node 5"])
# print(spl["node 3"]["node 6"])
# print(spl["node 3"]["node 7"])
# print(spl["node 3"]["node 8"])
# print(spl["node 3"]["node 10"])
# print(spl["node 3"]["node 11"])
# print(spl["node 3"]["node 12"])
# print(spl["node 3"]["node 13"])
# print(spl["node 3"]["node 14"])
# print(spl["node 3"]["node 15"])
# print(spl["node 3"]["node 16"])
# print(spl["node 3"]["node 17"])
# print(spl["node 3"]["node 18"])
# print(spl["node 3"]["node 19"])
# print(spl["node 3"]["node 20"])
# print(spl["node 3"]["node 21"])
# print(spl["node 3"]["node 22"])
# print(spl["node 3"]["node 23"])
# print(spl["node 3"]["node 24"])
# print(spl["node 3"]["node 25"])
# print(spl["node 3"]["node 26"])
# print(spl["node 3"]["node 27"])
# print(spl["node 3"]["node 29"])

# print(spl["node 4"]["node 1"])
# print(spl["node 4"]["node 2"])
# print(spl["node 4"]["node 3"])
# print(spl["node 4"]["node 4"])
# print(spl["node 4"]["node 5"])
# print(spl["node 4"]["node 6"])
# print(spl["node 4"]["node 7"])
# print(spl["node 4"]["node 8"])
# print(spl["node 4"]["node 10"])
# print(spl["node 4"]["node 11"])
# print(spl["node 4"]["node 12"])
# print(spl["node 4"]["node 13"])
# print(spl["node 4"]["node 14"])
# print(spl["node 4"]["node 15"])
# print(spl["node 4"]["node 16"])
# print(spl["node 4"]["node 17"])
# print(spl["node 4"]["node 18"])
# print(spl["node 4"]["node 19"])
# print(spl["node 4"]["node 20"])
# print(spl["node 4"]["node 21"])
# print(spl["node 4"]["node 22"])
# print(spl["node 4"]["node 23"])
# print(spl["node 4"]["node 24"])
# print(spl["node 4"]["node 25"])
# print(spl["node 4"]["node 26"])
# print(spl["node 4"]["node 27"])
# print(spl["node 4"]["node 29"])

# print(spl["node 5"]["node 1"])
# print(spl["node 5"]["node 2"])
# print(spl["node 5"]["node 3"])
# print(spl["node 5"]["node 4"])
# print(spl["node 5"]["node 5"])
# print(spl["node 5"]["node 6"])
# print(spl["node 5"]["node 7"])
# print(spl["node 5"]["node 8"])
# print(spl["node 5"]["node 10"])
# print(spl["node 5"]["node 11"])
# print(spl["node 5"]["node 12"])
# print(spl["node 5"]["node 13"])
# print(spl["node 5"]["node 14"])
# print(spl["node 5"]["node 15"])
# print(spl["node 5"]["node 16"])
# print(spl["node 5"]["node 17"])
# print(spl["node 5"]["node 18"])
# print(spl["node 5"]["node 19"])
# print(spl["node 5"]["node 20"])
# print(spl["node 5"]["node 21"])
# print(spl["node 5"]["node 22"])
# print(spl["node 5"]["node 23"])
# print(spl["node 5"]["node 24"])
# print(spl["node 5"]["node 25"])
# print(spl["node 5"]["node 26"])
# print(spl["node 5"]["node 27"])
# print(spl["node 5"]["node 29"])

# print(spl["node 6"]["node 1"])
# print(spl["node 6"]["node 2"])
# print(spl["node 6"]["node 3"])
# print(spl["node 6"]["node 4"])
# print(spl["node 6"]["node 5"])
# print(spl["node 6"]["node 6"])
# print(spl["node 6"]["node 7"])
# print(spl["node 6"]["node 8"])
# print(spl["node 6"]["node 10"])
# print(spl["node 6"]["node 11"])
# print(spl["node 6"]["node 12"])
# print(spl["node 6"]["node 13"])
# print(spl["node 6"]["node 14"])
# print(spl["node 6"]["node 15"])
# print(spl["node 6"]["node 16"])
# print(spl["node 6"]["node 17"])
# print(spl["node 6"]["node 18"])
# print(spl["node 6"]["node 19"])
# print(spl["node 6"]["node 20"])
# print(spl["node 6"]["node 21"])
# print(spl["node 6"]["node 22"])
# print(spl["node 6"]["node 23"])
# print(spl["node 6"]["node 24"])
# print(spl["node 6"]["node 25"])
# print(spl["node 6"]["node 26"])
# print(spl["node 6"]["node 27"])
# print(spl["node 6"]["node 29"])

# print(spl["node 7"]["node 1"])
# print(spl["node 7"]["node 2"])
# print(spl["node 7"]["node 3"])
# print(spl["node 7"]["node 4"])
# print(spl["node 7"]["node 5"])
# print(spl["node 7"]["node 6"])
# print(spl["node 7"]["node 7"])
# print(spl["node 7"]["node 8"])
# print(spl["node 7"]["node 10"])
# print(spl["node 7"]["node 11"])
# print(spl["node 7"]["node 12"])
# print(spl["node 7"]["node 13"])
# print(spl["node 7"]["node 14"])
# print(spl["node 7"]["node 15"])
# print(spl["node 7"]["node 16"])
# print(spl["node 7"]["node 17"])
# print(spl["node 7"]["node 18"])
# print(spl["node 7"]["node 19"])
# print(spl["node 7"]["node 20"])
# print(spl["node 7"]["node 21"])
# print(spl["node 7"]["node 22"])
# print(spl["node 7"]["node 23"])
# print(spl["node 7"]["node 24"])
# print(spl["node 7"]["node 25"])
# print(spl["node 7"]["node 26"])
# print(spl["node 7"]["node 27"])
# print(spl["node 7"]["node 29"])

# print(spl["node 8"]["node 1"])
# print(spl["node 8"]["node 2"])
# print(spl["node 8"]["node 3"])
# print(spl["node 8"]["node 4"])
# print(spl["node 8"]["node 5"])
# print(spl["node 8"]["node 6"])
# print(spl["node 8"]["node 7"])
# print(spl["node 8"]["node 8"])
# print(spl["node 8"]["node 10"])
# print(spl["node 8"]["node 11"])
# print(spl["node 8"]["node 12"])
# print(spl["node 8"]["node 13"])
# print(spl["node 8"]["node 14"])
# print(spl["node 8"]["node 15"])
# print(spl["node 8"]["node 16"])
# print(spl["node 8"]["node 17"])
# print(spl["node 8"]["node 18"])
# print(spl["node 8"]["node 19"])
# print(spl["node 8"]["node 20"])
# print(spl["node 8"]["node 21"])
# print(spl["node 8"]["node 22"])
# print(spl["node 8"]["node 23"])
# print(spl["node 8"]["node 24"])
# print(spl["node 8"]["node 25"])
# print(spl["node 8"]["node 26"])
# print(spl["node 8"]["node 27"])
# print(spl["node 8"]["node 29"])

# print(spl["node 10"]["node 1"])
# print(spl["node 10"]["node 2"])
# print(spl["node 10"]["node 3"])
# print(spl["node 10"]["node 4"])
# print(spl["node 10"]["node 5"])
# print(spl["node 10"]["node 6"])
# print(spl["node 10"]["node 7"])
# print(spl["node 10"]["node 8"])
# print(spl["node 10"]["node 10"])
# print(spl["node 10"]["node 11"])
# print(spl["node 10"]["node 12"])
# print(spl["node 10"]["node 13"])
# print(spl["node 10"]["node 14"])
# print(spl["node 10"]["node 15"])
# print(spl["node 10"]["node 16"])
# print(spl["node 10"]["node 17"])
# print(spl["node 10"]["node 18"])
# print(spl["node 10"]["node 19"])
# print(spl["node 10"]["node 20"])
# print(spl["node 10"]["node 21"])
# print(spl["node 10"]["node 22"])
# print(spl["node 10"]["node 23"])
# print(spl["node 10"]["node 24"])
# print(spl["node 10"]["node 25"])
# print(spl["node 10"]["node 26"])
# print(spl["node 10"]["node 27"])
# print(spl["node 10"]["node 29"])

# print(spl["node 11"]["node 1"])
# print(spl["node 11"]["node 2"])
# print(spl["node 11"]["node 3"])
# print(spl["node 11"]["node 4"])
# print(spl["node 11"]["node 5"])
# print(spl["node 11"]["node 6"])
# print(spl["node 11"]["node 7"])
# print(spl["node 11"]["node 8"])
# print(spl["node 11"]["node 10"])
# print(spl["node 11"]["node 11"])
# print(spl["node 11"]["node 12"])
# print(spl["node 11"]["node 13"])
# print(spl["node 11"]["node 14"])
# print(spl["node 11"]["node 15"])
# print(spl["node 11"]["node 16"])
# print(spl["node 11"]["node 17"])
# print(spl["node 11"]["node 18"])
# print(spl["node 11"]["node 19"])
# print(spl["node 11"]["node 20"])
# print(spl["node 11"]["node 21"])
# print(spl["node 11"]["node 22"])
# print(spl["node 11"]["node 23"])
# print(spl["node 11"]["node 24"])
# print(spl["node 11"]["node 25"])
# print(spl["node 11"]["node 26"])
# print(spl["node 11"]["node 27"])
# print(spl["node 11"]["node 29"])


# print(spl["node 12"]["node 1"])
# print(spl["node 12"]["node 2"])
# print(spl["node 12"]["node 3"])
# print(spl["node 12"]["node 4"])
# print(spl["node 12"]["node 5"])
# print(spl["node 12"]["node 6"])
# print(spl["node 12"]["node 7"])
# print(spl["node 12"]["node 8"])
# print(spl["node 12"]["node 10"])
# print(spl["node 12"]["node 11"])
# print(spl["node 12"]["node 12"])
# print(spl["node 12"]["node 13"])
# print(spl["node 12"]["node 14"])
# print(spl["node 12"]["node 15"])
# print(spl["node 12"]["node 16"])
# print(spl["node 12"]["node 17"])
# print(spl["node 12"]["node 18"])
# print(spl["node 12"]["node 19"])
# print(spl["node 12"]["node 20"])
# print(spl["node 12"]["node 21"])
# print(spl["node 12"]["node 22"])
# print(spl["node 12"]["node 23"])
# print(spl["node 12"]["node 24"])
# print(spl["node 12"]["node 25"])
# print(spl["node 12"]["node 26"])
# print(spl["node 12"]["node 27"])
# print(spl["node 12"]["node 29"])

# print(spl["node 13"]["node 1"])
# print(spl["node 13"]["node 2"])
# print(spl["node 13"]["node 3"])
# print(spl["node 13"]["node 4"])
# print(spl["node 13"]["node 5"])
# print(spl["node 13"]["node 6"])
# print(spl["node 13"]["node 7"])
# print(spl["node 13"]["node 8"])
# print(spl["node 13"]["node 10"])
# print(spl["node 13"]["node 11"])
# print(spl["node 13"]["node 12"])
# print(spl["node 13"]["node 13"])
# print(spl["node 13"]["node 14"])
# print(spl["node 13"]["node 15"])
# print(spl["node 13"]["node 16"])
# print(spl["node 13"]["node 17"])
# print(spl["node 13"]["node 18"])
# print(spl["node 13"]["node 19"])
# print(spl["node 13"]["node 20"])
# print(spl["node 13"]["node 21"])
# print(spl["node 13"]["node 22"])
# print(spl["node 13"]["node 23"])
# print(spl["node 13"]["node 24"])
# print(spl["node 13"]["node 25"])
# print(spl["node 13"]["node 26"])
# print(spl["node 13"]["node 27"])
# print(spl["node 13"]["node 29"])

# print(spl["node 14"]["node 1"])
# print(spl["node 14"]["node 2"])
# print(spl["node 14"]["node 3"])
# print(spl["node 14"]["node 4"])
# print(spl["node 14"]["node 5"])
# print(spl["node 14"]["node 6"])
# print(spl["node 14"]["node 7"])
# print(spl["node 14"]["node 8"])
# print(spl["node 14"]["node 10"])
# print(spl["node 14"]["node 11"])
# print(spl["node 14"]["node 12"])
# print(spl["node 14"]["node 13"])
# print(spl["node 14"]["node 14"])
# print(spl["node 14"]["node 15"])
# print(spl["node 14"]["node 16"])
# print(spl["node 14"]["node 17"])
# print(spl["node 14"]["node 18"])
# print(spl["node 14"]["node 19"])
# print(spl["node 14"]["node 20"])
# print(spl["node 14"]["node 21"])
# print(spl["node 14"]["node 22"])
# print(spl["node 14"]["node 23"])
# print(spl["node 14"]["node 24"])
# print(spl["node 14"]["node 25"])
# print(spl["node 14"]["node 26"])
# print(spl["node 14"]["node 27"])
# print(spl["node 14"]["node 29"])


# print(spl["node 15"]["node 1"])
# print(spl["node 15"]["node 2"])
# print(spl["node 15"]["node 3"])
# print(spl["node 15"]["node 4"])
# print(spl["node 15"]["node 5"])
# print(spl["node 15"]["node 6"])
# print(spl["node 15"]["node 7"])
# print(spl["node 15"]["node 8"])
# print(spl["node 15"]["node 10"])
# print(spl["node 15"]["node 11"])
# print(spl["node 15"]["node 12"])
# print(spl["node 15"]["node 13"])
# print(spl["node 15"]["node 14"])
# print(spl["node 15"]["node 15"])
# print(spl["node 15"]["node 16"])
# print(spl["node 15"]["node 17"])
# print(spl["node 15"]["node 18"])
# print(spl["node 15"]["node 19"])
# print(spl["node 15"]["node 20"])
# print(spl["node 15"]["node 21"])
# print(spl["node 15"]["node 22"])
# print(spl["node 15"]["node 23"])
# print(spl["node 15"]["node 24"])
# print(spl["node 15"]["node 25"])
# print(spl["node 15"]["node 26"])
# print(spl["node 15"]["node 27"])
# print(spl["node 15"]["node 29"])


# print(spl["node 16"]["node 1"])
# print(spl["node 16"]["node 2"])
# print(spl["node 16"]["node 3"])
# print(spl["node 16"]["node 4"])
# print(spl["node 16"]["node 5"])
# print(spl["node 16"]["node 6"])
# print(spl["node 16"]["node 7"])
# print(spl["node 16"]["node 8"])
# print(spl["node 16"]["node 10"])
# print(spl["node 16"]["node 11"])
# print(spl["node 16"]["node 12"])
# print(spl["node 16"]["node 13"])
# print(spl["node 16"]["node 14"])
# print(spl["node 16"]["node 15"])
# print(spl["node 16"]["node 16"])
# print(spl["node 16"]["node 17"])
# print(spl["node 16"]["node 18"])
# print(spl["node 16"]["node 19"])
# print(spl["node 16"]["node 20"])
# print(spl["node 16"]["node 21"])
# print(spl["node 16"]["node 22"])
# print(spl["node 16"]["node 23"])
# print(spl["node 16"]["node 24"])
# print(spl["node 16"]["node 25"])
# print(spl["node 16"]["node 26"])
# print(spl["node 16"]["node 27"])
# print(spl["node 16"]["node 29"])


# print(spl["node 17"]["node 1"])
# print(spl["node 17"]["node 2"])
# print(spl["node 17"]["node 3"])
# print(spl["node 17"]["node 4"])
# print(spl["node 17"]["node 5"])
# print(spl["node 17"]["node 6"])
# print(spl["node 17"]["node 7"])
# print(spl["node 17"]["node 8"])
# print(spl["node 17"]["node 10"])
# print(spl["node 17"]["node 11"])
# print(spl["node 17"]["node 12"])
# print(spl["node 17"]["node 13"])
# print(spl["node 17"]["node 14"])
# print(spl["node 17"]["node 15"])
# print(spl["node 17"]["node 16"])
# print(spl["node 17"]["node 17"])
# print(spl["node 17"]["node 18"])
# print(spl["node 17"]["node 19"])
# print(spl["node 17"]["node 20"])
# print(spl["node 17"]["node 21"])
# print(spl["node 17"]["node 22"])
# print(spl["node 17"]["node 23"])
# print(spl["node 17"]["node 24"])
# print(spl["node 17"]["node 25"])
# print(spl["node 17"]["node 26"])
# print(spl["node 17"]["node 27"])
# print(spl["node 17"]["node 29"])


# print(spl["node 18"]["node 1"])
# print(spl["node 18"]["node 2"])
# print(spl["node 18"]["node 3"])
# print(spl["node 18"]["node 4"])
# print(spl["node 18"]["node 5"])
# print(spl["node 18"]["node 6"])
# print(spl["node 18"]["node 7"])
# print(spl["node 18"]["node 8"])
# print(spl["node 18"]["node 10"])
# print(spl["node 18"]["node 11"])
# print(spl["node 18"]["node 12"])
# print(spl["node 18"]["node 13"])
# print(spl["node 18"]["node 14"])
# print(spl["node 18"]["node 15"])
# print(spl["node 18"]["node 16"])
# print(spl["node 18"]["node 17"])
# print(spl["node 18"]["node 18"])
# print(spl["node 18"]["node 19"])
# print(spl["node 18"]["node 20"])
# print(spl["node 18"]["node 21"])
# print(spl["node 18"]["node 22"])
# print(spl["node 18"]["node 23"])
# print(spl["node 18"]["node 24"])
# print(spl["node 18"]["node 25"])
# print(spl["node 18"]["node 26"])
# print(spl["node 18"]["node 27"])
# print(spl["node 18"]["node 29"])


# print(spl["node 19"]["node 1"])
# print(spl["node 19"]["node 2"])
# print(spl["node 19"]["node 3"])
# print(spl["node 19"]["node 4"])
# print(spl["node 19"]["node 5"])
# print(spl["node 19"]["node 6"])
# print(spl["node 19"]["node 7"])
# print(spl["node 19"]["node 8"])
# print(spl["node 19"]["node 10"])
# print(spl["node 19"]["node 11"])
# print(spl["node 19"]["node 12"])
# print(spl["node 19"]["node 13"])
# print(spl["node 19"]["node 14"])
# print(spl["node 19"]["node 15"])
# print(spl["node 19"]["node 16"])
# print(spl["node 19"]["node 17"])
# print(spl["node 19"]["node 18"])
# print(spl["node 19"]["node 19"])
# print(spl["node 19"]["node 20"])
# print(spl["node 19"]["node 21"])
# print(spl["node 19"]["node 22"])
# print(spl["node 19"]["node 23"])
# print(spl["node 19"]["node 24"])
# print(spl["node 19"]["node 25"])
# print(spl["node 19"]["node 26"])
# print(spl["node 19"]["node 27"])
# print(spl["node 19"]["node 29"])


# print(spl["node 20"]["node 1"])
# print(spl["node 20"]["node 2"])
# print(spl["node 20"]["node 3"])
# print(spl["node 20"]["node 4"])
# print(spl["node 20"]["node 5"])
# print(spl["node 20"]["node 6"])
# print(spl["node 20"]["node 7"])
# print(spl["node 20"]["node 8"])
# print(spl["node 20"]["node 10"])
# print(spl["node 20"]["node 11"])
# print(spl["node 20"]["node 12"])
# print(spl["node 20"]["node 13"])
# print(spl["node 20"]["node 14"])
# print(spl["node 20"]["node 15"])
# print(spl["node 20"]["node 16"])
# print(spl["node 20"]["node 17"])
# print(spl["node 20"]["node 18"])
# print(spl["node 20"]["node 19"])
# print(spl["node 20"]["node 20"])
# print(spl["node 20"]["node 21"])
# print(spl["node 20"]["node 22"])
# print(spl["node 20"]["node 23"])
# print(spl["node 20"]["node 24"])
# print(spl["node 20"]["node 25"])
# print(spl["node 20"]["node 26"])
# print(spl["node 20"]["node 27"])
# print(spl["node 20"]["node 29"])



# print(spl["node 21"]["node 1"])
# print(spl["node 21"]["node 2"])
# print(spl["node 21"]["node 3"])
# print(spl["node 21"]["node 4"])
# print(spl["node 21"]["node 5"])
# print(spl["node 21"]["node 6"])
# print(spl["node 21"]["node 7"])
# print(spl["node 21"]["node 8"])
# print(spl["node 21"]["node 10"])
# print(spl["node 21"]["node 11"])
# print(spl["node 21"]["node 12"])
# print(spl["node 21"]["node 13"])
# print(spl["node 21"]["node 14"])
# print(spl["node 21"]["node 15"])
# print(spl["node 21"]["node 16"])
# print(spl["node 21"]["node 17"])
# print(spl["node 21"]["node 18"])
# print(spl["node 21"]["node 19"])
# print(spl["node 21"]["node 20"])
# print(spl["node 21"]["node 21"])
# print(spl["node 21"]["node 22"])
# print(spl["node 21"]["node 23"])
# print(spl["node 21"]["node 24"])
# print(spl["node 21"]["node 25"])
# print(spl["node 21"]["node 26"])
# print(spl["node 21"]["node 27"])
# print(spl["node 21"]["node 29"])



# print(spl["node 22"]["node 1"])
# print(spl["node 22"]["node 2"])
# print(spl["node 22"]["node 3"])
# print(spl["node 22"]["node 4"])
# print(spl["node 22"]["node 5"])
# print(spl["node 22"]["node 6"])
# print(spl["node 22"]["node 7"])
# print(spl["node 22"]["node 8"])
# print(spl["node 22"]["node 10"])
# print(spl["node 22"]["node 11"])
# print(spl["node 22"]["node 12"])
# print(spl["node 22"]["node 13"])
# print(spl["node 22"]["node 14"])
# print(spl["node 22"]["node 15"])
# print(spl["node 22"]["node 16"])
# print(spl["node 22"]["node 17"])
# print(spl["node 22"]["node 18"])
# print(spl["node 22"]["node 19"])
# print(spl["node 22"]["node 20"])
# print(spl["node 22"]["node 21"])
# print(spl["node 22"]["node 22"])
# print(spl["node 22"]["node 23"])
# print(spl["node 22"]["node 24"])
# print(spl["node 22"]["node 25"])
# print(spl["node 22"]["node 26"])
# print(spl["node 22"]["node 27"])
# print(spl["node 22"]["node 29"])

# print(spl["node 23"]["node 1"])
# print(spl["node 23"]["node 2"])
# print(spl["node 23"]["node 3"])
# print(spl["node 23"]["node 4"])
# print(spl["node 23"]["node 5"])
# print(spl["node 23"]["node 6"])
# print(spl["node 23"]["node 7"])
# print(spl["node 23"]["node 8"])
# print(spl["node 23"]["node 10"])
# print(spl["node 23"]["node 11"])
# print(spl["node 23"]["node 12"])
# print(spl["node 23"]["node 13"])
# print(spl["node 23"]["node 14"])
# print(spl["node 23"]["node 15"])
# print(spl["node 23"]["node 16"])
# print(spl["node 23"]["node 17"])
# print(spl["node 23"]["node 18"])
# print(spl["node 23"]["node 19"])
# print(spl["node 23"]["node 20"])
# print(spl["node 23"]["node 21"])
# print(spl["node 23"]["node 22"])
# print(spl["node 23"]["node 23"])
# print(spl["node 23"]["node 24"])
# print(spl["node 23"]["node 25"])
# print(spl["node 23"]["node 26"])
# print(spl["node 23"]["node 27"])
# print(spl["node 23"]["node 29"])

# print(spl["node 24"]["node 1"])
# print(spl["node 24"]["node 2"])
# print(spl["node 24"]["node 3"])
# print(spl["node 24"]["node 4"])
# print(spl["node 24"]["node 5"])
# print(spl["node 24"]["node 6"])
# print(spl["node 24"]["node 7"])
# print(spl["node 24"]["node 8"])
# print(spl["node 24"]["node 10"])
# print(spl["node 24"]["node 11"])
# print(spl["node 24"]["node 12"])
# print(spl["node 24"]["node 13"])
# print(spl["node 24"]["node 14"])
# print(spl["node 24"]["node 15"])
# print(spl["node 24"]["node 16"])
# print(spl["node 24"]["node 17"])
# print(spl["node 24"]["node 18"])
# print(spl["node 24"]["node 19"])
# print(spl["node 24"]["node 20"])
# print(spl["node 24"]["node 21"])
# print(spl["node 24"]["node 22"])
# print(spl["node 24"]["node 23"])
# print(spl["node 24"]["node 24"])
# print(spl["node 24"]["node 25"])
# print(spl["node 24"]["node 26"])
# print(spl["node 24"]["node 27"])
# print(spl["node 24"]["node 29"])

# print(spl["node 25"]["node 1"])
# print(spl["node 25"]["node 2"])
# print(spl["node 25"]["node 3"])
# print(spl["node 25"]["node 4"])
# print(spl["node 25"]["node 5"])
# print(spl["node 25"]["node 6"])
# print(spl["node 25"]["node 7"])
# print(spl["node 25"]["node 8"])
# print(spl["node 25"]["node 10"])
# print(spl["node 25"]["node 11"])
# print(spl["node 25"]["node 12"])
# print(spl["node 25"]["node 13"])
# print(spl["node 25"]["node 14"])
# print(spl["node 25"]["node 15"])
# print(spl["node 25"]["node 16"])
# print(spl["node 25"]["node 17"])
# print(spl["node 25"]["node 18"])
# print(spl["node 25"]["node 19"])
# print(spl["node 25"]["node 20"])
# print(spl["node 25"]["node 21"])
# print(spl["node 25"]["node 22"])
# print(spl["node 25"]["node 23"])
# print(spl["node 25"]["node 24"])
# print(spl["node 25"]["node 25"])
# print(spl["node 25"]["node 26"])
# print(spl["node 25"]["node 27"])
# print(spl["node 25"]["node 29"])

# print(spl["node 26"]["node 1"])
# print(spl["node 26"]["node 2"])
# print(spl["node 26"]["node 3"])
# print(spl["node 26"]["node 4"])
# print(spl["node 26"]["node 5"])
# print(spl["node 26"]["node 6"])
# print(spl["node 26"]["node 7"])
# print(spl["node 26"]["node 8"])
# print(spl["node 26"]["node 10"])
# print(spl["node 26"]["node 11"])
# print(spl["node 26"]["node 12"])
# print(spl["node 26"]["node 13"])
# print(spl["node 26"]["node 14"])
# print(spl["node 26"]["node 15"])
# print(spl["node 26"]["node 16"])
# print(spl["node 26"]["node 17"])
# print(spl["node 26"]["node 18"])
# print(spl["node 26"]["node 19"])
# print(spl["node 26"]["node 20"])
# print(spl["node 26"]["node 21"])
# print(spl["node 26"]["node 22"])
# print(spl["node 26"]["node 23"])
# print(spl["node 26"]["node 24"])
# print(spl["node 26"]["node 25"])
# print(spl["node 26"]["node 26"])
# print(spl["node 26"]["node 27"])
# print(spl["node 26"]["node 29"])

# print(spl["node 27"]["node 1"])
# print(spl["node 27"]["node 2"])
# print(spl["node 27"]["node 3"])
# print(spl["node 27"]["node 4"])
# print(spl["node 27"]["node 5"])
# print(spl["node 27"]["node 6"])
# print(spl["node 27"]["node 7"])
# print(spl["node 27"]["node 8"])
# print(spl["node 27"]["node 10"])
# print(spl["node 27"]["node 11"])
# print(spl["node 27"]["node 12"])
# print(spl["node 27"]["node 13"])
# print(spl["node 27"]["node 14"])
# print(spl["node 27"]["node 15"])
# print(spl["node 27"]["node 16"])
# print(spl["node 27"]["node 17"])
# print(spl["node 27"]["node 18"])
# print(spl["node 27"]["node 19"])
# print(spl["node 27"]["node 20"])
# print(spl["node 27"]["node 21"])
# print(spl["node 27"]["node 22"])
# print(spl["node 27"]["node 23"])
# print(spl["node 27"]["node 24"])
# print(spl["node 27"]["node 25"])
# print(spl["node 27"]["node 26"])
# print(spl["node 27"]["node 27"])
# print(spl["node 27"]["node 29"])

print(spl["node 29"]["node 1"])
print(spl["node 29"]["node 2"])
print(spl["node 29"]["node 3"])
print(spl["node 29"]["node 4"])
print(spl["node 29"]["node 5"])
print(spl["node 29"]["node 6"])
print(spl["node 29"]["node 7"])
print(spl["node 29"]["node 8"])
print(spl["node 29"]["node 10"])
print(spl["node 29"]["node 11"])
print(spl["node 29"]["node 12"])
print(spl["node 29"]["node 13"])
print(spl["node 29"]["node 14"])
print(spl["node 29"]["node 15"])
print(spl["node 29"]["node 16"])
print(spl["node 29"]["node 17"])
print(spl["node 29"]["node 18"])
print(spl["node 29"]["node 19"])
print(spl["node 29"]["node 20"])
print(spl["node 29"]["node 21"])
print(spl["node 29"]["node 22"])
print(spl["node 29"]["node 23"])
print(spl["node 29"]["node 24"])
print(spl["node 29"]["node 25"])
print(spl["node 29"]["node 26"])
print(spl["node 29"]["node 27"])
print(spl["node 29"]["node 29"])

