import networkx as nx
import matplotlib.pyplot as plt
G = nx.Graph()

G.add_nodes_from([("node 1", {"name": "disjoint"}), ("node 2", {"name": "disjointTouch"}),
                  ("node 3", {"name": "meet"}), ("node 4", {"name": "overlapMeet"}),
                  ("node 5", {"name": "overlap"}), ("node 6", {"name": "overlapCoveredBy"}),
                  ("node 7", {"name": "overlapCovers"}), ("node 8", {"name": "coveredBy"}),
                  ("node 9", {"name": "overlapFully"}), ("node 10", {"name": "covers"}),
                  ("node 11", {"name": "insideTouch"}), ("node 12", {"name": "coveredByFully"}),
                  ("node 13", {"name": "coversFully"}), ("node 14", {"name": "containsTouch"}),
                  ("node 15", {"name": "inside"}), ("node 16", {"name": "insideTotal"}),
                  ("node 17", {"name": "equals"}), ("node 18", {"name": "containsTotal"}),
                  ("node 19", {"name": "contains"}), ("node 20", {"name": "embrace"}),
                  ("node 21", {"name": "embraceFully"}), ("node 22", {"name": "attach"}),
                  ("node 23", {"name": "disjointTotal"}), ("node 24", {"name": "embraceTouch"}),
                  ("node 25", {"name": "entwinedFully"}), ("node 26", {"name": "meetFully"}),
                  ("node 27", {"name": "entwined"}), ("node 28", {"name": "overlapMinimally"}),
                  ("node 29", {"name": "overlapEntwined"})

                  ])
# Side 1
G.add_edge("node 1", "node 2")
G.add_edge("node 2", "node 3")
G.add_edge("node 3", "node 4")
G.add_edge("node 4", "node 5")
G.add_edge("node 5", "node 6")
G.add_edge("node 6", "node 8")
G.add_edge("node 8", "node 11")
G.add_edge("node 11", "node 15")

# Side 2
G.add_edge("node 20", "node 24")
G.add_edge("node 24", "node 27")
G.add_edge("node 27", "node 29")
G.add_edge("node 29", "node 5")
G.add_edge("node 5", "node 7")
G.add_edge("node 7", "node 10")
G.add_edge("node 10", "node 14")
G.add_edge("node 14", "node 19")

# Top 1
G.add_edge("node 27", "node 25")
G.add_edge("node 25", "node 22")
G.add_edge("node 22", "node 26")
G.add_edge("node 26", "node 3")

# Top 2
G.add_edge("node 8", "node 12")
G.add_edge("node 12", "node 17")
G.add_edge("node 17", "node 13")
G.add_edge("node 13", "node 10")


nx.draw(G)
plt.show()


# 21
# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])


# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])


# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])


# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])


# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])


# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])


# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])



# print(spl["node 1"]["node 1"])
# print(spl["node 1"]["node 2"])
# print(spl["node 1"]["node 3"])
# print(spl["node 1"]["node 4"])
# print(spl["node 1"]["node 5"])
# print(spl["node 1"]["node 6"])
# print(spl["node 1"]["node 7"])
# print(spl["node 1"]["node 8"])
# print(spl["node 1"]["node 9"])
# print(spl["node 1"]["node 10"])
# print(spl["node 1"]["node 11"])
# print(spl["node 1"]["node 14"])
# print(spl["node 1"]["node 15"])
# print(spl["node 1"]["node 17"])
# print(spl["node 1"]["node 19"])
# print(spl["node 1"]["node 20"])
# print(spl["node 1"]["node 22"])
# print(spl["node 1"]["node 24"])
# print(spl["node 1"]["node 27"])
# print(spl["node 1"]["node 28"])
# print(spl["node 1"]["node 29"])

